##################
# Theme settings #
##################

remote_theme: sudharkj/material-jekyll

#################
# Site settings #
#################

profile-link: https://mdbootstrap.com/img/Photos/Others/photo6.jpg
avatar-link: https://github.githubassets.com/images/modules/logos_page/Octocat.png
name: Sudha Ravi Kumar Javvadi
title: Programmer
caption: 2nd year Master's Student at Oregon State University actively looking for software fulltime or internship opportunities in the field of Computer Vision, Natural Language Processing, or Machine Learning.

#######################
# Attachment settings #
#######################

attachment-text: Resume
attachment-link: https://drive.google.com/file/d/1CZDbjT3MqZBo6k3ZUIvth-y-tyBlFK-k/view?usp=sharing

################
# Social Links #
################

linkedin: https://www.linkedin.com/in/sudharkj/
github: https://github.com/sudharkj

################
# Page Details #
################

show-table-of-contents: true
landing-page-order: posts/projects.md