##################
# Theme settings #
##################

remote_theme: sudharkj/material-jekyll

#################
# Site settings #
#################

profile-color: indigo
avatar-link: https://avatars3.githubusercontent.com/u/8425883
name: Sudha Ravi Kumar Javvadi
title: Programmer
caption: CS graduate working as SDE2 at Oracle interested in projects related to the field of Computer Vision, Natural Language Processing, and Reinforcement Learning.

#######################
# Attachment settings #
#######################

attachment-text: Resume
attachment-link: https://drive.google.com/file/d/1CZDbjT3MqZBo6k3ZUIvth-y-tyBlFK-k/view

################
# Social Links #
################

linkedin: https://www.linkedin.com/in/sudharkj/
github: https://github.com/sudharkj

################
# Page Details #
################

show-table-of-contents: false
landing-page-order: posts/projects.md, posts/other-projects.md
